<?php


    namespace App\Domain\Account;

    use App\Domain\AbstractModel;
    use Mockery\Exception;

    class Membership extends AbstractModel
    {
        const NEW_MEMBER = 1;

        /**
         * @var array
         */
        protected $columns = [
            'account_id' => [
                'type' => 'int',
                'required' => true
            ],
            "subscription_id" => [
                'type' => 'int',
                'required' => true
            ],
            "created_at" => [
                "type" => "date",
                "required" => false
            ],
            "updated_at" => [
                "type" => "date",
                "required" => false
            ],
            "meta" => [
                "type" => "json",
                "required" => false
            ]
        ];

        /**
         * @param array|string $id
         * @param string $idField
         * @return $this|AbstractModel|Membership
         * @throws \ReflectionException
         */
      public function load($id, $idField = self::ID_FIELD)
      {
        $sub = $this->getSubscription();
        $join = sprintf('LEFT JOIN %s s ON m.%s = s.%s', $sub->getName(), 'subscription_id', $sub::ID_FIELD);

        $data = null;
        if(method_exists($this->getDb(), 'getRow')) {
            $data = $this->getDb()::getRow(
                sprintf('SELECT *,m.* FROM %s m %s WHERE %s=? LIMIT 1', $this->getName(), $join, $idField),
                [$id]
            );
        }

        if($data) {
          $this->data[self::ID_FIELD] = $data[self::ID_FIELD];
          foreach ($this->columns as $name => $value) {
            $this->data[$name] = $data[$name] ?? null;
            unset($data[$name]);
          }
        }

        $this->children['subscription'] = $data;

        return $this;
      }

        /**
         * Merge any noew json into meta property, might be a problem in the future, as
         * no way to delete a json key
         * @param array $values
         * @return array
         */
        public function beforeSave(array $values, array $raw = []): array
        {

            $subscription = $this->getSubscription();

            if (!isset($values["subscription_id"])) {
                $values["subscription_id"] = $subscription->getFreeTrialId();
            }

            /**
             * Generate expiry date if the subscription has an expiration date
             */
            $expiration_days = $subscription->load($values["subscription_id"])->getExpiryDays();
            if($expiration_days) {
              $values["expires_at"] = $subscription->getExpirationDateByDays($expiration_days);
            }

            $meta = $values["meta"] ?? [];
            if (is_array($meta) && isset($this->data["meta"])) {
                $json = json_decode($this->data["meta"], true);
                if (is_array($json)) {
                    $meta = array_merge($json, $meta);
                }
            }
            if(is_array($meta)) {
                $values["meta"] = json_encode($meta);
            }
            return parent::beforeSave($values, $raw); // TODO: Change the autogenerated stub
        }

        /**
         * @return Subscription
         */
        public function getSubscription() {
            return new Subscription();
        }

      /**
       * @param array $filters
       * @throws \Exception
       */
      public function applyFilters(string $sql, array $filters) : string
      {

        $sql = parent::applyFilters($sql, $filters);

        $clauses = [];

        /*
         * Filter by created at
         */

        if ( isset($filters['created_at_start']) ) {
          $clauses[] = "CAST(created_at AS Date) >= '" . $filters['created_at_start'] . "'";
        }

        /*
         * Filter by end date
         */
        if ( isset($filters['created_at_end']) ) {
          $clauses[] = "CAST(created_at AS Date) <= '" . $filters['created_at_end'] . "'";
        }

        if($clauses){
          $sql .= $this->sql_filters ? ' AND ' : ' WHERE ';
          $sql .= implode(" AND ", $clauses);
        }

        return $sql;
      }
    }
