import * as Yup from 'yup';
import { ValidationSchemes } from '../../clink';
import {
  DATE_FORMAT_PLACEHOLDER,
  DATE_FORMAT,
} from '../../../helpers/constants';

const GENERAL_INFO = {
  INITIAL_VALUES: {
    name: '',
    reference: '',
    start: '',
    end: '',
    phase: {},
    region: {},
    type: {},
    description: {
      editorHtml: '',
      files: [],
    },
    projectImage: '',
  },
  FORM_FIELDS: [
    {
      key: 'name',
      type: 'text',
      name: 'name',
      label: 'Project name',
      className: 'name',
      placeholder: 'Project name',
      required: true,
    },
    {
      key: 'reference',
      type: 'text',
      name: 'reference',
      label: 'Project reference',
      className: 'reference',
      placeholder: 'Project reference',
      required: true,
    },
    {
      key: 'start',
      type: 'text',
      name: 'start',
      label: 'Start date',
      className: 'start-date',
      dateFormat: DATE_FORMAT,
      placeholder: DATE_FORMAT_PLACEHOLDER,
      calendar: true,
      required: true,
    },
    {
      key: 'end',
      type: 'text',
      name: 'end',
      label: 'Completion date',
      className: 'completion-date',
      dateFormat: DATE_FORMAT,
      placeholder: DATE_FORMAT_PLACEHOLDER,
      calendar: true,
      required: true,
    },
    {
      key: 'phase',
      as: 'select',
      name: 'phase',
      label: 'Status',
      className: 'status',
      options: [],
      placeholder: 'Please select a status',
      required: true,
    },
    {
      key: 'region',
      as: 'select',
      name: 'region',
      label: 'Location',
      className: 'location',
      options: [],
      placeholder: 'Please select a location',
      required: true,
    },
    {
      key: 'type',
      as: 'select',
      name: 'type',
      label: 'Type',
      className: 'type',
      options: [],
      placeholder: 'Please select a type',
      required: true,
    },
    {
      key: 'description',
      type: 'editor',
      name: 'description',
      label: 'Project description',
      className: 'description',
      placeholder: 'Add a short description about your project',
    },
    {
      key: 'projectImage',
      type: 'file',
      name: 'projectImage',
      label: 'Project image',
      className: 'project-image',
      accept: 'image/*',
    },
  ],
  VALIDATION_SCHEMA: Yup.object().shape({
    name: ValidationSchemes.basicText,
    reference: ValidationSchemes.basicText,
    start: ValidationSchemes.basicDate,
    end: ValidationSchemes.basicDate,
    phase: ValidationSchemes.select,
    region: ValidationSchemes.select,
    type: ValidationSchemes.select,
    projectImage: ValidationSchemes.file,
  }),
};

export default GENERAL_INFO;
