<?php

/**
 * Generate `documentation/middleware-catalog.md`.
 *
 * This script scans directories under `framework/src/<app>/code/Middleware/` for PHP classes and
 * lists public static methods that return callable-like types (callable/Callable/Closure/\Closure).
 *
 * Usage:
 *   php scripts/generate_framework_middleware_catalog.php
 */

/**
 * @return array{file:string,line:int,className:?string,methodName:string,returnType:string}
 */
function middleware_factory(string $file, int $line, ?string $className, string $methodName, string $returnType): array
{
    return [
        'file' => $file,
        'line' => $line,
        'className' => $className,
        'methodName' => $methodName,
        'returnType' => $returnType,
    ];
}

function repo_root(): string
{
    return dirname(__DIR__);
}

function framework_src_root(): string
{
    return repo_root() . DIRECTORY_SEPARATOR . 'framework' . DIRECTORY_SEPARATOR . 'src';
}

function normalize_path(string $path): string
{
    return str_replace('\\', '/', $path);
}

function relpath(string $path, string $root): string
{
    $root = rtrim(normalize_path($root), '/');
    $path = normalize_path($path);
    if (str_starts_with($path, $root . '/')) {
        return substr($path, strlen($root) + 1);
    }
    return $path;
}

function find_middleware_dirs(string $frameworkSrc): array
{
    $dirs = [];
    $it = new RecursiveIteratorIterator(
        new RecursiveDirectoryIterator($frameworkSrc, FilesystemIterator::SKIP_DOTS),
        RecursiveIteratorIterator::SELF_FIRST
    );
    foreach ($it as $fileInfo) {
        if (!$fileInfo instanceof SplFileInfo) {
            continue;
        }
        if (!$fileInfo->isDir()) {
            continue;
        }
        $path = normalize_path($fileInfo->getPathname());
        if (str_ends_with($path, '/code/Middleware')) {
            $dirs[$path] = true;
        }
    }
    $out = array_keys($dirs);
    sort($out);
    return $out;
}

function app_name_from_file(string $file, string $repoRoot): string
{
    // Expected: framework/src/<app>/code/Middleware/...
    $rel = normalize_path(relpath($file, $repoRoot));
    $parts = explode('/', $rel);
    $srcIdx = array_search('src', $parts, true);
    if ($srcIdx !== false && isset($parts[$srcIdx + 1])) {
        return $parts[$srcIdx + 1];
    }
    return 'unknown';
}

function extract_class_name(string $text): ?string
{
    if (preg_match('/\bclass\s+([A-Za-z_][A-Za-z0-9_]*)\b/', $text, $m)) {
        return $m[1];
    }
    return null;
}

function count_newlines_before(string $text, int $pos): int
{
    // 1-based line number
    return substr_count(substr($text, 0, $pos), "\n") + 1;
}

function extract_factories_from_text(string $file, string $text): array
{
    $factories = [];
    $className = extract_class_name($text);

    $needle = 'public static function';
    $offset = 0;
    while (true) {
        $sigStart = strpos($text, $needle, $offset);
        if ($sigStart === false) {
            break;
        }

        $brace = strpos($text, '{', $sigStart);
        if ($brace === false) {
            break;
        }

        $signature = substr($text, $sigStart, $brace - $sigStart);

        if (!preg_match('/public\s+static\s+function\s+([A-Za-z_][A-Za-z0-9_]*)\s*\(/', $signature, $mName)) {
            $offset = $brace + 1;
            continue;
        }
        $methodName = $mName[1];

        $returnType = '';
        if (preg_match('/\)\s*:\s*([\\\\A-Za-z0-9_|]+)/', $signature, $mType)) {
            $returnType = $mType[1];
        }

        $returnTypeLower = strtolower($returnType);
        $isCallableLike = (
            str_contains($returnTypeLower, 'callable') ||
            str_contains($returnTypeLower, 'closure')
        );

        if ($isCallableLike) {
            $line = count_newlines_before($text, $sigStart);
            $factories[] = middleware_factory(
                file: $file,
                line: $line,
                className: $className,
                methodName: $methodName,
                returnType: $returnType !== '' ? $returnType : '(no return type)',
            );
        }

        $offset = $brace + 1;
    }

    return $factories;
}

function scan_php_files(array $phpFiles): array
{
    $results = [];
    foreach ($phpFiles as $file) {
        $text = @file_get_contents($file);
        if (!is_string($text)) {
            continue;
        }
        foreach (extract_factories_from_text($file, $text) as $factory) {
            $results[] = $factory;
        }
    }
    return $results;
}

function render_markdown(string $repoRoot, array $factories): string
{
    $out = [];
    $out[] = '# Reusable Middleware Catalog';
    $out[] = '';
    $out[] = 'This file is generated by `scripts/generate_framework_middleware_catalog.php`.';
    $out[] = 'It lists middleware factory methods (public static methods returning `callable`/`Callable`/`Closure`) under `framework/src/**/code/Middleware/**`.';
    $out[] = '';
    $out[] = '## How to use this';
    $out[] = '';
    $out[] = '- When implementing a new endpoint, check if a middleware already exists for the task (fetching common entities, ownership checks, REST passthrough, etc.).';
    $out[] = '- In route files, middleware entries are callables, so you typically add factories like `Rest::fetchDynamic(...)` or `Generic::set(...)` to the `middleware` array.';
    $out[] = '- If you create new reusable middleware, add it under the appropriate `framework/src/<app>/code/Middleware/` directory and regenerate this catalog.';
    $out[] = '';
    $out[] = '## Index';
    $out[] = '';
    $out[] = '- Core utilities: `framework/src/core/code/Middleware/`';
    $out[] = '- API-specific utilities: `framework/src/api/code/Middleware/`';
    $out[] = '- Other apps: `framework/src/*/code/Middleware/`';
    $out[] = '';
    $out[] = '## Catalog';
    $out[] = '';

    usort($factories, function (array $a, array $b) use ($repoRoot): int {
        $ak = [
            app_name_from_file($a['file'], $repoRoot),
            relpath($a['file'], $repoRoot),
            $a['className'] ?? '',
            $a['methodName'],
            $a['line'],
        ];
        $bk = [
            app_name_from_file($b['file'], $repoRoot),
            relpath($b['file'], $repoRoot),
            $b['className'] ?? '',
            $b['methodName'],
            $b['line'],
        ];
        return $ak <=> $bk;
    });

    $currentApp = null;
    $currentFile = null;
    foreach ($factories as $f) {
        $app = app_name_from_file($f['file'], $repoRoot);
        $rel = relpath($f['file'], $repoRoot);

        if ($currentApp !== $app) {
            $currentApp = $app;
            $currentFile = null;
            $out[] = "### {$app}";
            $out[] = '';
        }

        if ($currentFile !== $f['file']) {
            $currentFile = $f['file'];
            $out[] = "#### `{$rel}`";
            $out[] = '';
        }

        $prefix = $f['className'] ? ($f['className'] . '::') : '';
        $out[] = "- `{$prefix}{$f['methodName']}()` \u{2192} `{$f['returnType']}` (`{$rel}:{$f['line']}`)";
    }

    $out[] = '';
    return implode("\n", $out);
}

function main(): int
{
    $startedAt = microtime(true);
    $repoRoot = repo_root();
    $frameworkSrc = framework_src_root();
    $outFile = $repoRoot . DIRECTORY_SEPARATOR . 'documentation' . DIRECTORY_SEPARATOR . 'middleware-catalog.md';

    fwrite(STDOUT, "Generating framework middleware catalog...\n");
    fwrite(STDOUT, "Scanning: " . relpath($frameworkSrc, $repoRoot) . "\n");

    $middlewareDirs = find_middleware_dirs($frameworkSrc);
    fwrite(STDOUT, "Found middleware dirs: " . count($middlewareDirs) . "\n");

    $phpFiles = [];
    foreach ($middlewareDirs as $dir) {
        $it = new RecursiveIteratorIterator(
            new RecursiveDirectoryIterator($dir, FilesystemIterator::SKIP_DOTS)
        );
        foreach ($it as $fileInfo) {
            if (!$fileInfo instanceof SplFileInfo) {
                continue;
            }
            if ($fileInfo->isFile() && str_ends_with($fileInfo->getFilename(), '.php')) {
                $phpFiles[] = $fileInfo->getPathname();
            }
        }
    }

    fwrite(STDOUT, "Found PHP files: " . count($phpFiles) . "\n");

    $factories = scan_php_files($phpFiles);
    fwrite(STDOUT, "Found middleware factories: " . count($factories) . "\n");

    $md = render_markdown($repoRoot, $factories);

    if (@file_put_contents($outFile, $md) === false) {
        fwrite(STDERR, "Failed to write {$outFile}\n");
        return 1;
    }

    $durationMs = (int) round((microtime(true) - $startedAt) * 1000);
    fwrite(STDOUT, "Wrote: " . relpath($outFile, $repoRoot) . " ({$durationMs}ms)\n");
    return 0;
}

exit(main());
