<?php

    namespace App\Domain\Tests;

    use App\Domain\AbstractTypeModel;

    class TestTypeModel extends  AbstractTypeModel {
        public function findAll(array $filters = [], int $limit = 0, int $offset = 0, bool $assoc_array = false): array {
            return [
                ["label" => "test", "id" => 1],
                ["label" => "test2", "id" => 2],
                ["label" => "test3", "id" => 3],
                ["label" => "test4", "id" => 4]
            ];
        }
    }

    class TestAbstractTypeModel extends \PHPUnit\Framework\TestCase
    {
        protected $model;

        public function setUp(): void
        {
            $this->model = new TestTypeModel();
            parent::setUp(); // TODO: Change the autogenerated stub
        }

        public function testCanGetLabel(){

            $label =  $this->model->getLabel(2);
            $this->assertEquals($label, "test2");
        }

        public function testCanGetId() {
            $this->assertEquals( $this->model->getLabelId("test4"
            ), 4);
        }
    }
