// Mock for @mui/x-date-pickers/AdapterDayjs
export const AdapterDayjs = function AdapterDayjs() {
  // Mock adapter for dayjs
  return {
    locale: 'en',
    date: (value) => value,
    parse: (value, format) => value,
    format: (value, format) => value,
    formatByString: (value, format) => value,
    isEqual: (value, comparing) => value === comparing,
    isNull: (value) => value === null,
    isAfter: (value, comparing) => false,
    isAfterDay: (value, comparing) => false,
    isAfterYear: (value, comparing) => false,
    isBefore: (value, comparing) => false,
    isBeforeDay: (value, comparing) => false,
    isBeforeYear: (value, comparing) => false,
    isSame: (value, comparing) => value === comparing,
    isSameDay: (value, comparing) => false,
    isSameMonth: (value, comparing) => false,
    isSameYear: (value, comparing) => false,
    isValid: (value) => value != null,
    getDiff: (value, comparing) => 0,
    isWithinRange: (value, range) => false,
    startOfDay: (value) => value,
    startOfMonth: (value) => value,
    startOfWeek: (value) => value,
    startOfYear: (value) => value,
    endOfDay: (value) => value,
    endOfMonth: (value) => value,
    endOfWeek: (value) => value,
    endOfYear: (value) => value,
    addYears: (value, amount) => value,
    addMonths: (value, amount) => value,
    addWeeks: (value, amount) => value,
    addDays: (value, amount) => value,
    addHours: (value, amount) => value,
    addMinutes: (value, amount) => value,
    addSeconds: (value, amount) => value,
    getYear: (value) => 2024,
    getMonth: (value) => 0,
    getDate: (value) => 1,
    getHours: (value) => 0,
    getMinutes: (value) => 0,
    getSeconds: (value) => 0,
    setYear: (value, year) => value,
    setMonth: (value, month) => value,
    setDate: (value, date) => value,
    setHours: (value, hours) => value,
    setMinutes: (value, minutes) => value,
    setSeconds: (value, seconds) => value,
    getNextMonth: (value) => value,
    getPreviousMonth: (value) => value,
    getMonthArray: (value) => [],
    getWeekdays: () => [],
    getWeekArray: (value) => [],
    getYearRange: (start, end) => [],
    getMeridiemText: (meridiem) => meridiem,
  };
};

module.exports = { AdapterDayjs };
